### ISSUE TITLE
Style main navigation

### ISSUE THREAD

**Issue by wayferer** [borna761/ClusterMaps#21]
- [x] Logo
- [x] Nav

**Comment by wayferer** [comment]
@borna761 are you happy with this?

**Comment by borna761** [comment]
@wayferer is it supposed to look like this?
![image](https://cloud.githubusercontent.com/assets/9056534/18816303/791cb1c0-8314-11e6-9245-9fa86896573c.png)

**Comment by wayferer** [comment]
@borna761 more like this

![image](https://cloud.githubusercontent.com/assets/1575559/18816307/ec073478-8303-11e6-9bb9-f90c685a8ec0.png)

any errors in your console?

**Comment by borna761** [comment]
@wayferer This seems to be on heroku as well... not sure what's going on?

**Comment by wayferer** [comment]
@borna761 just saw this in the build log

```
Detected manifest file, assuming assets were compiled locally
```

Did you add something new that would stop heroku from compiling the assets? No worries if you did, you'll just have to run

```
RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by borna761** [comment]
@wayferer looks great!

**Comment by wayferer** [comment]
Yay!
