### ISSUE TITLE
Style Clusters page

### ISSUE THREAD

**Issue by wayferer** [borna761/ClusterMaps#23]

**Comment by wayferer** [comment]
@borna761 suggestions based on what is there now?

**Comment by borna761** [comment]
@wayferer, I really like it, so I'm sorry if all of this comes off as negative:
- The space between the lines look a bit tight, and make it top-aligned:
  ![image](https://cloud.githubusercontent.com/assets/9056534/18818075/2dcb97d4-833e-11e6-8246-3eb3bf169c28.png)
- Make "Share" green, and the "Delete" button a bit more red
  ![image](https://cloud.githubusercontent.com/assets/9056534/18818081/8e03b672-833e-11e6-9003-2ac865d1dc49.png)

**Comment by wayferer** [comment]
Not negative at all! I have made some updates

**Comment by borna761** [comment]
Can we increase the distance between the rows here?
![image](https://cloud.githubusercontent.com/assets/9056534/18970912/2a81fcf0-8661-11e6-88f7-ebca90c867d7.png)

Also the distance between the dropdowns and the buttons?
![image](https://cloud.githubusercontent.com/assets/9056534/18970937/3e33d1a6-8661-11e6-83c3-9eccc0c05b70.png)
![image](https://cloud.githubusercontent.com/assets/9056534/18970949/49143002-8661-11e6-9d7d-ee7d54d89002.png)

Should we center these?
![image](https://cloud.githubusercontent.com/assets/9056534/18970964/53c9f1da-8661-11e6-8a8e-7d11d1dc6264.png)

This is the same color as Change Owner - do we want to have it different?
![image](https://cloud.githubusercontent.com/assets/9056534/18970977/5df8a71e-8661-11e6-9f95-c4f78a39eee2.png)

**Comment by borna761** [comment]
@wayferer I think it's good!
