### ISSUE TITLE
Style Home page

### ISSUE THREAD

**Issue by wayferer** [borna761/ClusterMaps#25]
- [x] Map
- [x] Map legend
- [x] Map controls

**Comment by borna761** [comment]
@wayferer I really like what you've done with this: ![this](https://cloud.githubusercontent.com/assets/1575559/18317450/72beb216-74db-11e6-91e3-1a8a76a13db6.png)

and of course, it should be a table as you said. other than that, I'm thinking something simple like what we have, just a bit prettier. the map and legend, and listing the stuff on the right.

do you have any thoughts?

**Comment by wayferer** [comment]
@borna761 I tried putting it on the right of the map but it started looking bad as I added more sample data with wrapping etc. Having it at the bottom of the map means that there will be plenty of space for long names etc. I'm going to put that data into a table and lets see how it looks.

**Comment by borna761** [comment]
@wayferer alright, hmmm... then we might need to make the height of the map smaller or something, so it's visible at the bottom that it's clickable. other option I guess would be to make the width smaller as well to make sure the wrapping isn't too bad. what do you think?

**Comment by wayferer** [comment]
@borna761 for sure I can make the map shorter but I'm hesitant to make it less wide as I'm thinking about some of the larger communities that would have many activities happening and I feel a large map would make it easier when zooming in to have more places visible. What do you think?

**Comment by borna761** [comment]
@wayferer I have a feeling a zoomed out view would be sufficient. when they zoom in it would be on a neighborhood level anyway, no?

**Comment by wayferer** [comment]
Good point. Is it ok if I leave the home page for now and focus on the other pages and then come back to this?

**Comment by borna761** [comment]
Sure, go for it!

**Comment by borna761** [comment]
I would consider dropping the height of the map by a bit.
Something like this should probably be enough, no?
![image](https://cloud.githubusercontent.com/assets/9056534/18816575/9f9679ca-831a-11e6-9c24-84f202de7526.png)

**Comment by wayferer** [comment]
@borna761 I dropped the height a bit

**Comment by borna761** [comment]
@wayferer I really like it!

**Comment by wayferer** [comment]
Yay!
