### ISSUE TITLE
GMaps error

### ISSUE THREAD

**Issue by wayferer** [borna761/ClusterMaps#36]
Getting the following error when loading the home page once logged in:

````
Your site URL to be authorized: http://localhost:3000/
````

https://www.google.ca/search?q=Your+site+URL+to+be+authorized%3A+http%3A%2F%2Flocalhost%3A3000%2F&oq=Your+site+URL+to+be+authorized%3A+http%3A%2F%2Flocalhost%3A3000%2F&aqs=chrome..69i57.359j0j4&sourceid=chrome&ie=UTF-8

**Comment by wayferer** [comment]
Seems to be working fine on https://clustermaps.herokuapp.com/

**Comment by borna761** [comment]
Sent you a key.
